server:
  port: 9002
spring:
  application:
    name: originfriend-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/originfriend_recruit?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true