server:
  port: 9003
spring:
  application:
    name: originfriend-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/originfriend_qa?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true