server:
  port: 9004
spring:
  application:
    name: originfriend-article #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/originfriend_article?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.15.50
    password: